### ISSUE TITLE
can i use this for xbt?

### ISSUE THREAD

**Issue by rottenronin1** [5ymph0en1x/SyDOM#3]
how can i use this for xbtusd trading pair? thanks!

**Comment by 5ymph0en1x** [comment]
You need to adjust the settings `instrument_bmex` at the beginning of sydom.py by changing its value ('XBTUSD' in your case).

Don't forget to change `model_thr_1` and `model_thr_2` according to the graph once the model has been generated...

Best regards

**Comment by rottenronin1** [comment]
changing model_thr_1 and 2 in sydom.py? which graph to use? does this need to be changed every day since the bot auto generates a model everyday? thanks!
